### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MaikoTan** [MaikoTan/nixos-config#3]
Things that are remaining migrating from Arch Linux:

## Packages

- [ ] alsa-lib
- [ ] android-studio
- [ ] android-tools
- [ ] appmenu-gtk-module
- [ ] ~~arch-install-scripts~~
- [ ] aria2
- [ ] ark
- [ ] baobab
- [ ] ~~base~~
- [ ] ~~base-devel~~
- [x] base16384
- [ ] bind
- [ ] blender-3.6-bin
- [ ] bluez-obex
- [ ] bluez-utils
- [ ] clash
- [ ] cmake
- [x] cups
- [ ] devtools
- [ ] dingtalk-bin
- [ ] direnv
- [ ] discord
- [ ] docker
- [ ] docker-compose
- [ ] dosfstools
- [ ] dotnet-sdk
- [ ] ~~downgrade~~
- [ ] dprint
- [x] efibootmgr
- [ ] epiphany
- [ ] evince
- [ ] exfatprogs
- [ ] extension-manager
- [x] fcitx5
- [x] fcitx5-configtool
- [x] fcitx5-gtk
- [ ] fcitx5-qt
- [x] fcitx5-rime
- [ ] filezilla
- [ ] firefox
- [x] fish
- [ ] fuse2
- [x] gdm
- [ ] gifsicle
- [ ] gimp
- [x] git
- [ ] git-cliff
- [ ] git-filter-repo
- [ ] github-cli
- [ ] gnome (series)
- [ ] gnome-shell
- [x] gnome-shell-extension-dash-to-dock
- [x] gnome-shell-extension-kimpanel-git
- [ ] gnome-shell-extension-unite
- [ ] gnome-shell-extension-wallhub
- [ ] gnome-shell-extensions
- [ ] gnu-netcat
- [x] google-chrome
- [ ] grilo-plugins
- [x] grub
- [ ] gvfs-afc
- [ ] gvfs-goa
- [ ] gvfs-google
- [ ] gvfs-gphoto2
- [ ] gvfs-mtp
- [ ] gvfs-nfs
- [ ] gvfs-smb
- [x] htop
- [ ] inetutils
- [ ] inkscape
- [ ] jdk11-openjdk
- [ ] konsole
- [ ] kpipewire
- [ ] ksnip
- [ ] layer-shell-qt
- [x] libreoffice-fresh
- [x] librime
- [x] linux
- [x] linux-firmware
- [x] linux-headers
- [ ] linuxqq
- [ ] llvm
- [ ] localsearch
- [ ] loupe
- [ ] malcontent
- [ ] man-db
- [ ] mingw-w64-binutils
- [ ] mingw-w64-crt
- [ ] mingw-w64-gcc
- [ ] mingw-w64-headers
- [ ] mingw-w64-winpthreads
- [ ] mkcert
- [ ] mumble
- [ ] mumble-server
- [ ] namcap
- [ ] nano
- [x] nautilus (GNOME app)
- [ ] neofetch
- [ ] net-tools
- [ ] netease-cloud-music
- [x] networkmanager
- [ ] ninja
- [ ] nodejs
- [ ] noto-fonts-emoji
- [ ] noto-fonts-sc
- [ ] npm
- [ ] orca
- [ ] os-prober
- [ ] parsec-bin
- [ ] peek
- [ ] pipewire-alsa
- [ ] pipewire-jack
- [ ] pipewire-pulse
- [ ] playonlinux
- [ ] postman-bin
- [ ] python-pip
- [ ] python-pysmbc
- [ ] qpwgraph
- [ ] qt5-webengine
- [ ] reflector
- [x] rime-double-pinyin
- [x] rime-japanese
- [ ] rime-luna-pinyin
- [ ] rpm-tools
- [ ] rsync
- [ ] rustup
- [ ] rygel
- [ ] simple-scan
- [ ] snapshot
- [ ] spectacle
- [ ] steam
- [x] sudo
- [ ] sunloginclient
- [x] sushi (GNOME app)
- [ ] system-config-printer
- [x] tecla (GNOME app)
- [ ] todesk-bin
- [ ] totem
- [ ] translate-toolkit
- [x] transmission-qt
- [x] ttf-fira-code
- [x] ttf-jetbrains-mono
- [x] ttf-ms-fonts
- [ ] vagrant
- [ ] vim
- [x] virtualbox
- [x] virtualbox-guest-iso
- [ ] virtualbox-host-modules-arch
- [ ] virtualfish
- [x] visual-studio-code-insiders-bin
- [ ] vpl-gpu-rt
- [x] wechat-devtools-git
- [ ] wemeet-bin
- [ ] winetricks
- [ ] wireplumber
- [ ] xdg-desktop-portal-gnome
- [ ] xdg-user-dirs-gtk
- [ ] yakuake
- [ ] ~~yay~~
- [ ] yelp
- [x] yq
- [x] zerotier-one
